const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `The homey goodness of plain golden pancakes served with whipped butter. You'll go nuts over these rich and flavorful buttermilk pancakes.`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Our lunch menu offers salads, sandwiches, quiche, soup and fries options. Pair with a beer or wine for the perfect lunch. `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Indulge in our creamy and delicious milkshakes, made with real ice cream and your choice of flavors.  Perfect to cool down on a hot summer day or as a dessert after a meal.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Start your day off right with our delicious egg sandwich breakfast. Made with freshly-cracked eggs and your choice of bacon, sausage or ham. Add avocado or tomato for a tasty twist. Perfect for a hearty breakfast on the go.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Try our delicious egg and beef burger, made with a juicy beef patty and a fried egg on top. Served on a toasted bun with lettuce, tomato and cheese. Perfect for brunch or lunch, this burger is sure to satisfy your cravings.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Satisfy your sweet tooth with our rich and indulgent chocolate milkshake. Made with premium chocolate ice cream and topped with whipped cream and chocolate sauce. Perfect for a hot day or as a dessert.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Wake up to our tasty egg and bacon sandwich. Made with freshly-cracked eggs, crispy bacon and served on a toasted bread. Add cheese, lettuce and tomato for a tasty twist. Perfect for a satisfying breakfast on the go.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Try our classic American burger made with 100% beef patty, lettuce, tomato, onion, pickles, cheese and special sauce. Served on a toasted bun. Perfect for a satisfying lunch or dinner.  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Share a creamy and delicious milkshake made with real ice cream and your choice of flavor. Try our classic vanilla or chocolate, or go for something unique like strawberry or mint chocolate chip.`,
  },
];
export default menu;
